name: meilisearch_ui
description: The official meilisearch ui kit
version: 0.0.1
homepage: https://www.meilisearch.com
repository: https://github.com/meilisearch/meilisearch-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.10.0

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  meilisearch: ^0.14.0
  #TODO: remove rxdart dependency
  rxdart: ^0.27.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rxdart: ^0.27.7
flutter: